# Generated by Django 2.1.7 on 2019-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='游戏id')),
                ('game_name', models.CharField(max_length=100, verbose_name='游戏名称')),
                ('category', models.CharField(choices=[('speed', '速通'), ('score', '贪分'), ('challenge', '挑战')], default='speed', max_length=20, verbose_name='游戏类型')),
                ('video_url', models.CharField(max_length=254, verbose_name='录像地址')),
                ('rank', models.IntegerField(default=1, verbose_name='排名')),
                ('player', models.CharField(max_length=30, verbose_name='玩家')),
                ('timestamp', models.CharField(blank=True, max_length=30, null=True, verbose_name='时长')),
                ('video_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='日期')),
                ('platform', models.CharField(max_length=30, verbose_name='分类')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'db_table': 'rank',
                'ordering': ['game_name', 'rank'],
            },
        ),
    ]
